theme: minima
title: Pineapple Pizza Codes ✨
author: Ilona Loučková
email: ilona.louckova@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  24-year-old techie based in Prague, Czechia. 
  I studied economics and management before deciding to pursue a career in IT instead
  as I'm a passionate learner who enjoys being challenged and striving for continuous improvement.
  With 2+ years' experience; networking and technical support,
  not too long ago I started to direct my attention towards system administration and coding.
  ... Let's see where this thing goes.

# social links
twitter_username: IlonaLouckova # DO NOT include the @ character, or else the build will fail!
github_username:  IlonaLouckova # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
